name: cinemapedia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  card_swiper: ^3.0.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.4.10
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.1.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  build_runner: ^2.4.12
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FBFAEE"
  adaptive_icon_foreground: "assets/icon/app-icon.png"

flutter_native_splash:
  color: "#FBFAEE"
  image: assets/icon/app-icon.png
  color_dark: "#141400"
  image_dark: assets/icon/app-icon.png
  android: true
  ios: true
  
  # add this
  android_12:
    icon_background_color: "#FBFAEE"
    image: assets/icon/app-icon.png
    icon_background_color_dark: "#141400"
    image_dark: assets/icon/app-icon.png
    android: true
    ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
